In [1]:
import pandas as pd

df = pd.read_pickle("processed_data/service_cavia_mean.pkl")
df

,Distribution,Scenario,App_ms,Service_ID,Node_Type,Cavia_Mean,Num_Runs,Empirical_Mean,Empirical_Std,Empirical_Min,Empirical_Max,Abs_Error,Rel_Error_Percent
0,deterministic,1_26_solution_v0,1SMM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
1,deterministic,1_26_solution_v0,1SMM,1,perception_preprocessing,4.0,100,4.00,0.000000,4,4,0.00,0.000000
2,deterministic,1_26_solution_v0,1SMM,2,feature_extraction,4.0,100,4.00,0.000000,4,4,0.00,0.000000
3,deterministic,1_26_solution_v0,1SMM,3,context_awareness,10.0,100,10.00,0.000000,10,10,0.00,0.000000
4,deterministic,1_26_solution_v0,1SMM,4,avda,9.0,100,9.00,0.000000,9,9,0.00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543,uniform,2_26_solution_v7,2SMS,5,feature_extraction,4.0,100,3.39,1.109145,2,5,0.61,15.250000
2544,uniform,2_26_solution_v7,2SMS,6,context_awareness,10.0,100,9.19,2.525406,5,14,0.81,8.100000
2545,uniform,2_26_solution_v7,2SMS,7,planning_and_decision,6.0,100,5.32,1.728431,3,8,0.68,11.333333
2546,uniform,2_26_solution_v7,2SMS,8,actuation,4.0,100,3.40,1.128152,2,5,0.60,15.000000
2547,uniform,2_26_solution_v7,2SMS,9,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000

In [2]:
print(f"Total rows: {len(df)}")
print(f"Distributions: {df['Distribution'].nunique()}")
print(f"Scenarios: {df['Scenario'].nunique()}")
print(f"App: {df[['Scenario', 'App_ms']].drop_duplicates().shape[0]}")
print(f"Average percentage error: {df['Rel_Error_Percent'].mean():.2f}")
print(f"Maximum percentage error: {df['Rel_Error_Percent'].max():.2f}")
print(f"Average percentage error per distribution:\n {df.groupby('Distribution')['Rel_Error_Percent'].mean().round(2)}")

Total rows: 2548
Distributions: 7
Scenarios: 10
App: 48
Average percentage error: 5.85
Maximum percentage error: 31.25
Average percentage error per distribution:
 Distribution
deterministic         0.00
exponential           6.34
gamma_k2              6.60
normal                6.67
normal_wide           3.47
normal_wide_trunc    11.29
uniform               6.60
Name: Rel_Error_Percent, dtype: float64

In [3]:
df_exp = df[df['Distribution'] == 'exponential']
df_exp.head(20)

,Distribution,Scenario,App_ms,Service_ID,Node_Type,Cavia_Mean,Num_Runs,Empirical_Mean,Empirical_Std,Empirical_Min,Empirical_Max,Abs_Error,Rel_Error_Percent
364,exponential,1_26_solution_v0,1SMM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
365,exponential,1_26_solution_v0,1SMM,1,perception_preprocessing,4.0,100,4.36,4.676440,1,24,0.36,9.000000
366,exponential,1_26_solution_v0,1SMM,2,feature_extraction,4.0,100,4.22,4.291358,1,22,0.22,5.500000
367,exponential,1_26_solution_v0,1SMM,3,context_awareness,10.0,100,9.50,9.010095,1,49,0.50,5.000000
368,exponential,1_26_solution_v0,1SMM,4,avda,9.0,100,9.39,9.399006,1,49,0.39,4.333333
369,exponential,1_26_solution_v0,1SMM,5,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000
370,exponential,1_26_solution_v0,1SMS,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
371,exponential,1_26_solution_v0,1SMS,1,perception_preprocessing,4.0,100,4.31,4.184374,1,22,0.31,7.750000
372,exponential,1_26_solution_v0,1SMS,2,feature_extraction,4.0,100,3.51,3.748387,1,17,0.49,12.250000
373,exponential,1_26_solution_v0,1SMS,3,context_awareness,10.0,100,12.92,13.244156,1,83,2.92,29.200000
374,exponential,1_26_solution_v0,1SMS,4,planning_and_decision,6.0,100,6.61,6.316397,1,30,0.61,10.166667
375,exponential,1_26_solution_v0,1SMS,5,actuation,4.0,100,4.37,4.777166,1,26,0.37,9.250000
376,exponential,1_26_solution_v0,1SMS,6,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000
377,exponential,1_26_solution_v0,1SSM,0,input,0.0,100,0.00,0.000000,0,0,0.00,0.000000
378,exponential,1_26_solution_v0,1SSM,1,perception_preprocessing,4.0,100,3.61,3.501500,1,18,0.39,9.750000
379,exponential,1_26_solution_v0,1SSM,2,feature_extraction,4.0,100,3.40,3.690008,1,18,0.60,15.000000
380,exponential,1_26_solution_v0,1SSM,3,sensor_fusion,6.0,100,5.53,5.531279,1,28,0.47,7.833333
381,exponential,1_26_solution_v0,1SSM,4,map_content,5.0,100,5.27,5.391454,1,25,0.27,5.400000
382,exponential,1_26_solution_v0,1SSM,5,avda,9.0,100,7.63,7.896624,1,36,1.37,15.222222
383,exponential,1_26_solution_v0,1SSM,6,destination,0.0,100,0.00,0.000000,0,0,0.00,0.000000